<!DOCTYPE html>
<html>
<head>
    <title>This Email generated by CloudZoom</title>
</head>
<body>
    <h1>{{ $details['title'] }}</h1>
    <p>Hi, {{$details['name']}} <br> Your password reset otp is <strong>{{ $details['otp'] }}</strong></p>
    <p>Thank you</p>
</body>
</html>
